---
system:
  name: Binance
  market: binance #binance.py
  test: False
  logs: True
  version: 3
market:
  lot_size: 25
  asset_currency: EUR
modules:
 - name : executive
   downstream: 
    - port: 2000
      bind: False
      type: PUB
      name: EXEC_DOWN
 - name : market
   tick_module_port: 2000
   downstream:
    - port: 3000
      bind: True
   defualt_tick_sources:
   - RT
   - 1m
   - 3m
   - 5m
tickers:
 - name: "DOGE"
   enabled: True
   algorithms:
    - name: echo
      enabled: True
 - name: "SHIB"
   enabled: False
   algorithms:
    - name: echo
      enabled: True
 - name: "BTC"
   enabled: True
   algorithms:
    - name: echo
      enabled: True
 - name: "ETH"
   enabled: True
   algorithms:
    - name: echo
      enabled: True
proxies:
 - name: log_proxy
   upstream: 9000
   downstream: 10000

    
      
     