---
system:
  name: Binance
  market: binance #binance.py
  test: False
  logs: True
  version: 3
  algorithm_base_port: 4050
  max_supported_algorithms_per_ticker: 10
market:
  lot_size: 25
  asset_currency: EUR
modules:
 - name : executive
   downstream: 
    - port: 2000
      bind: False
      type: PUB
      name: EXEC_DOWN
 - name : market
   downstream_base_port: 3000 
   enabled_tick_sources:
   - RT
   - 1m
   - 3m
   - 5m
  - name: manager
    ticker_base_port: 4000
    ticker_offset_port: 100 #Offset
tickers:
 - name: "DOGE"
   enabled: True
   algorithms:
    - name: echo
      enabled: True
 - name: "SHIB"
   enabled: False
   algorithms:
    - name: echo
      enabled: True
 - name: "BTC"
   enabled: True
   algorithms:
    - name: echo
      enabled: True
 - name: "ETH"
   enabled: True
   algorithms:
    - name: echo
      enabled: True
proxies:
 - name: log_proxy
   upstream: 9000
   downstream: 10000

    
      
     