---
system:
  name: F_Trader Binance
  test: True
  logs: True
  version: 3
  base_market_port: 3000
  base_market_offset: 100
  base_ticker_port: 4000
  base_ticker_offset: 100
  max_supported_algorithms_per_ticker: 50 # 0 -> 49
  algorithm_proxy_offset: 50
  account_offset: 51
  broker_port: 5000
  trader_port: 6000
  logger_port: 10000
  logger_proxy_port: 9000
  viewer: False
  viewer_port: 11000
markets:
- name: Binance
  enabled: True
  enabled_tick_sources:
  - RT
  - 1m
  - 3m
  - 5m
- name: Alpaca
  enabled: False
  enabled_tick_sources:
  - RT
  - 1m
  - 3m
  - 5m
tickers:
 - name: "DOGEEUR"
   enabled: True
   required_data: "All"
   algorithms:
    - name: scalp
      enabled: True
      config:
       window: 10
       target_growth: 1.04
 - name: "SHIBEUR"
   enabled: False
   algorithms:
    - name: echo
      enabled: True
    - name: scalp
      enabled: True
      config:
       window: 5
       target_growth: 1.03

    
      
     