---
system:
  name: Binance
  test: False
  logs: True
  version: 3
  lot_size: 25
  algorithm_base_port: 4000
  algorithm_port_increment: 100
  algorithm_proxy_offset: 51
  algorithm_account_offset: 52
  account_broker_port: 5000
  log_proxy_port: 9000
  log_port: 10000
modules:
 - name : executive
   downstream: 
    - port: 2000
      bind: False
      type: PUB
      name: EXEC_DOWN
 - name : market
   tick_module_port: 2000
   downstream:
    - port: 3000
      bind: True2
   tick_sources:
   - RT
   - 1m
   - 3m
   - 5m
tickers: # Each Ticker comes with a Proxy and an Account Node!
 - name: "DOGEUSDT"
   enabled: True
   algorithms:
    - name: echo
      enabled: True
 - name: "SHIBUSDT"
   enabled: False
   algorithms:
    - name: echo
      enabled: True
 - name: "BTC"
   enabled: True
   algorithms:
    - name: echo
      enabled: True
 - name: "ETHUSDT"
   enabled: True
   algorithms:
    - name: echo
      enabled: True
proxies:
 - name: log_proxy
   upstream: 9000
   downstream: 10000

    
      
     